In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
processed_df=pd.read_csv("processed_data.csv", low_memory=False)

In [4]:
# EXtracting the columns which I really needs for the GNN part

gnn_columns = [
    
    "Accident_Index",
    "Latitude",
    "Longitude",


    "1st_Road_Number",
    "2nd_Road_Number",
    "Speed_limit",

   
    "Year",
    "Month",
    "Day",
    "Hour",
    "Is_Weekend",
    "Is_Rush_Hour",
    "Is_Peak_Hour",
    "Is_Night",
    "Is_Morning",
    "Is_Evening",

    
    "Bad_Weather_Flag",
    "Poor_Visibility_Flag",
]

In [5]:
prefixes = [
    "Road_Type_",
    "1st_Road_Class_",
    "2nd_Road_Class_",
    "Junction_Control_",
    "Junction_Detail_",
    "Weather_Conditions_",
    "Road_Surface_Conditions_",
    "Light_Conditions_",
    "Urban_or_Rural_Area_",
    "Traffic_Density_Indicator_",
    "Season_"
]

for col in processed_df.columns:
    for prefix in prefixes: 
        if col.startswith(prefix):
            if col not in gnn_columns:
                gnn_columns.append(col)
            break;

In [6]:
gnn_df = processed_df[gnn_columns].copy()

In [7]:
gnn_df.head()

,Accident_Index,Latitude,Longitude,1st_Road_Number,2nd_Road_Number,Speed_limit,Year,Month,Day,Hour,...,Junction_Detail_Crossroads,Junction_Detail_Mini-Roundabout,Junction_Detail_More Than 4 Arms (Not Roundabout),Junction_Detail_Not At Junction Or Within 20 Metres,Junction_Detail_Other Junction,Junction_Detail_Private Drive Or Entrance,Junction_Detail_Roundabout,Junction_Detail_Slip Road,Junction_Detail_T Or Staggered Junction,Junction_Detail_Unknown
0,200501Bs00001,51.489096,-0.191170,3218.0,0.0,30.0,2005.0,4.0,1.0,17.0,...,0,0,0,1,0,0,0,0,0,0
1,200501Bs00002,51.520075,-0.211708,450.0,0.0,30.0,2005.0,5.0,1.0,17.0,...,1,0,0,0,0,0,0,0,0,0
2,200501Bs00003,51.525301,-0.206458,0.0,0.0,30.0,2005.0,6.0,1.0,0.0,...,0,0,0,1,0,0,0,0,0,0
3,200501Bs00004,51.482442,-0.173862,3220.0,0.0,30.0,2005.0,7.0,1.0,10.0,...,0,0,0,1,0,0,0,0,0,0
4,200501Bs00005,51.495752,-0.156618,0.0,0.0,30.0,2005.0,10.0,1.0,21.0,...,0,0,0,1,0,0,0,0,0,0

In [8]:
gnn_df.to_csv("gnn_accident_dataset.csv", index=False)

In [9]:
print(gnn_df.shape)

(2047244, 86)

In [10]:
print(gnn_df.columns.tolist())

['Accident_Index', 'Latitude', 'Longitude', '1st_Road_Number', '2nd_Road_Number', 'Speed_limit', 'Year', 'Month', 'Day', 'Hour', 'Is_Weekend', 'Is_Rush_Hour', 'Is_Peak_Hour', 'Is_Night', 'Is_Morning', 'Is_Evening', 'Bad_Weather_Flag', 'Poor_Visibility_Flag', 'Urban_or_Rural_Area_Rural', 'Urban_or_Rural_Area_Unallocated', 'Urban_or_Rural_Area_Urban', 'Traffic_Density_Indicator_Single_Vehicle', 'Traffic_Density_Indicator_Two_Vehicle', 'Traffic_Density_Indicator_Moderate', 'Traffic_Density_Indicator_High_Density', 'Season_Autumn', 'Season_Spring', 'Season_Summer', 'Season_Unknown', 'Season_Winter', 'Road_Type_Dual Carriageway', 'Road_Type_One Way Street', 'Road_Type_Roundabout', 'Road_Type_Single Carriageway', 'Road_Type_Slip Road', 'Road_Type_Unknown', 'Road_Surface_Conditions_Dry', 'Road_Surface_Conditions_Flood Over 3Cm. Deep', 'Road_Surface_Conditions_Frost Or Ice', 'Road_Surface_Conditions_Snow', 'Road_Surface_Conditions_Unknown', 'Road_Surface_Conditions_Wet Or Damp', '1st_Road_Class_A', '1st_Road_Class_A(M)', '1st_Road_Class_B', '1st_Road_Class_C', '1st_Road_Class_Motorway', '1st_Road_Class_Unclassified', 'Light_Conditions_Darkness - Lighting Unknown', 'Light_Conditions_Darkness - Lights Lit', 'Light_Conditions_Darkness - Lights Unlit', 'Light_Conditions_Darkness - No Lighting', 'Light_Conditions_Daylight', 'Light_Conditions_Unknown', 'Junction_Control_Authorised Person', 'Junction_Control_Auto Traffic Signal', 'Junction_Control_Give Way Or Uncontrolled', 'Junction_Control_Not At Junction Or Within 20 Metres', 'Junction_Control_Stop Sign', 'Junction_Control_Unknown', '2nd_Road_Class_A', '2nd_Road_Class_A(M)', '2nd_Road_Class_B', '2nd_Road_Class_C', '2nd_Road_Class_Motorway', '2nd_Road_Class_Unclassified', '2nd_Road_Class_Unknown', 'Weather_Conditions_Fine + High Winds', 'Weather_Conditions_Fine No High Winds', 'Weather_Conditions_Fog Or Mist', 'Weather_Conditions_Other', 'Weather_Conditions_Raining + High Winds', 'Weather_Conditions_Raining No High Winds', 'Weather_Conditions_Snowing + High Winds', 'Weather_Conditions_Snowing No High Winds', 'Weather_Conditions_Unknown', 'Junction_Detail_Crossroads', 'Junction_Detail_Mini-Roundabout', 'Junction_Detail_More Than 4 Arms (Not Roundabout)', 'Junction_Detail_Not At Junction Or Within 20 Metres', 'Junction_Detail_Other Junction', 'Junction_Detail_Private Drive Or Entrance', 'Junction_Detail_Roundabout', 'Junction_Detail_Slip Road', 'Junction_Detail_T Or Staggered Junction', 'Junction_Detail_Unknown']

In [11]:
print(gnn_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2047244 entries, 0 to 2047243
Data columns (total 86 columns):
 #   Column                                                Dtype
---  ------                                                -----
 0   Accident_Index                                        object
 1   Latitude                                              float64
 2   Longitude                                             float64
 3   1st_Road_Number                                       float64
 4   2nd_Road_Number                                       float64
 5   Speed_limit                                           float64
 6   Year                                                  float64
 7   Month                                                 float64
 8   Day                                                   float64
 9   Hour                                                  float64
 10  Is_Weekend                                            int64
 11  Is_Rush_Hour                                          int64
 12  Is_Peak_Hour                                          int64
 13  Is_Night                                              int64
 14  Is_Morning                                            int64
 15  Is_Evening                                            int64
 16  Bad_Weather_Flag                                      int64
 17  Poor_Visibility_Flag                                  int64
 18  Urban_or_Rural_Area_Rural                             int64
 19  Urban_or_Rural_Area_Unallocated                       int64
 20  Urban_or_Rural_Area_Urban                             int64
 21  Traffic_Density_Indicator_Single_Vehicle              int64
 22  Traffic_Density_Indicator_Two_Vehicle                 int64
 23  Traffic_Density_Indicator_Moderate                    int64
 24  Traffic_Density_Indicator_High_Density                int64
 25  Season_Autumn                                         int64
 26  Season_Spring                                         int64
 27  Season_Summer                                         int64
 28  Season_Unknown                                        int64
 29  Season_Winter                                         int64
 30  Road_Type_Dual Carriageway                            int64
 31  Road_Type_One Way Street                              int64
 32  Road_Type_Roundabout                                  int64
 33  Road_Type_Single Carriageway                          int64
 34  Road_Type_Slip Road                                   int64
 35  Road_Type_Unknown                                     int64
 36  Road_Surface_Conditions_Dry                           int64
 37  Road_Surface_Conditions_Flood Over 3Cm. Deep          int64
 38  Road_Surface_Conditions_Frost Or Ice                  int64
 39  Road_Surface_Conditions_Snow                          int64
 40  Road_Surface_Conditions_Unknown                       int64
 41  Road_Surface_Conditions_Wet Or Damp                   int64
 42  1st_Road_Class_A                                      int64
 43  1st_Road_Class_A(M)                                   int64
 44  1st_Road_Class_B                                      int64
 45  1st_Road_Class_C                                      int64
 46  1st_Road_Class_Motorway                               int64
 47  1st_Road_Class_Unclassified                           int64
 48  Light_Conditions_Darkness - Lighting Unknown          int64
 49  Light_Conditions_Darkness - Lights Lit                int64
 50  Light_Conditions_Darkness - Lights Unlit              int64
 51  Light_Conditions_Darkness - No Lighting               int64
 52  Light_Conditions_Daylight                             int64
 53  Light_Conditions_Unknown                              int64
 54  Junction_Control_Authorised Person                    int64
 55  Junction_Control_Auto Traffic Signal                  int64
 56  Junction_Control_Give Way Or Uncontrolled             int64
 57  Junction_Control_Not At Junction Or Within 20 Metres  int64
 58  Junction_Control_Stop Sign                            int64
 59  Junction_Control_Unknown                              int64
 60  2nd_Road_Class_A                                      int64
 61  2nd_Road_Class_A(M)                                   int64
 62  2nd_Road_Class_B                                      int64
 63  2nd_Road_Class_C                                      int64
 64  2nd_Road_Class_Motorway                               int64
 65  2nd_Road_Class_Unclassified                           int64
 66  2nd_Road_Class_Unknown                                int64
 67  Weather_Conditions_Fine + High Winds                  int64
 68  Weather_Conditions_Fine No High Winds                 int64
 69  Weather_Conditions_Fog Or Mist                        int64
 70  Weather_Conditions_Other                              int64
 71  Weather_Conditions_Raining + High Winds               int64
 72  Weather_Conditions_Raining No High Winds              int64
 73  Weather_Conditions_Snowing + High Winds               int64
 74  Weather_Conditions_Snowing No High Winds              int64
 75  Weather_Conditions_Unknown                            int64
 76  Junction_Detail_Crossroads                            int64
 77  Junction_Detail_Mini-Roundabout                       int64
 78  Junction_Detail_More Than 4 Arms (Not Roundabout)     int64
 79  Junction_Detail_Not At Junction Or Within 20 Metres   int64
 80  Junction_Detail_Other Junction                        int64
 81  Junction_Detail_Private Drive Or Entrance             int64
 82  Junction_Detail_Roundabout                            int64
 83  Junction_Detail_Slip Road                             int64
 84  Junction_Detail_T Or Staggered Junction               int64
 85  Junction_Detail_Unknown                               int64
dtypes: float64(9), int64(76), object(1)
memory usage: 1.3+ GB
None

In [12]:
print(gnn_df.dtypes.value_counts())

int64      76
float64     9
object      1
Name: count, dtype: int64

In [13]:
missing = (gnn_df.isna().sum().sort_values(ascending=False))

missing[missing > 0]

Year     1230156
Month    1230156
Day      1230156
Hour         156
dtype: int64

In [14]:
missing_report = pd.DataFrame(
    {
    "missing_count": gnn_df.isna().sum(),
    "missing_percentage": gnn_df.isna().mean() * 100
    }
)

missing_report = missing_report.sort_values("missing_percentage",ascending=False)

missing_report

                            missing_count  missing_percentage
Year                              1230156           60.088392
Month                             1230156           60.088392
Day                               1230156           60.088392
Hour                                  156            0.007620
Accident_Index                          0            0.000000
...                                   ...                 ...
Road_Type_Dual Carriageway              0            0.000000
Season_Winter                           0            0.000000
Season_Unknown                          0            0.000000
Season_Summer                           0            0.000000
Junction_Detail_Unknown                 0            0.000000

[86 rows x 2 columns]

In [15]:
print("Duplicate rows:", gnn_df.duplicated().sum())

Duplicate rows: 0

In [16]:
print("Total rows:", len(gnn_df))

print("Unique Accident_Index:", gnn_df["Accident_Index"].nunique())

print("Duplicate Accident_Index:", gnn_df["Accident_Index"].duplicated().sum())

Total rows: 2047244
Unique Accident_Index: 2047244
Duplicate Accident_Index: 0

In [17]:
print("Latitude missing:", gnn_df["Latitude"].isna().sum())

print("Longitude missing:", gnn_df["Longitude"].isna().sum())

Latitude missing: 0
Longitude missing: 0

In [18]:
print(gnn_df[["Latitude", "Longitude"]].describe())

           Latitude     Longitude
count  2.047244e+06  2.047244e+06
mean   5.255975e+01 -1.410152e+00
std    1.445450e+00  1.403474e+00
min    4.991294e+01 -7.516225e+00
25%    5.148541e+01 -2.329505e+00
50%    5.223759e+01 -1.362233e+00
75%    5.345586e+01 -2.052988e-01
max    6.075754e+01  1.762010e+00

In [19]:
invalid_lat = ((gnn_df["Latitude"] < -90) | (gnn_df["Latitude"] > 90))

invalid_lon = ((gnn_df["Longitude"] < -180) | (gnn_df["Longitude"] > 180))

print("Invalid latitude:", invalid_lat.sum())
print("Invalid longitude:", invalid_lon.sum())

Invalid latitude: 0
Invalid longitude: 0

In [20]:
# Printing the Latitude range from min value to max value
print("Latitude:",gnn_df["Latitude"].min(),"to",gnn_df["Latitude"].max())

# Printing the Longitude range from min value to max value;
print("Longitude:",gnn_df["Longitude"].min(),"to",gnn_df["Longitude"].max())

Latitude: 49.912941 to 60.757544
Longitude: -7.516225 to 1.76201

In [21]:
print(gnn_df["Year"].value_counts().sort_index())

Year
2005.0    77780
2006.0    76138
2007.0    71866
2008.0    70163
2009.0    66172
2010.0    60742
2011.0    61437
2012.0    56335
2013.0    55822
2014.0    59068
2015.0    55520
2016.0    54710
2017.0    51335
Name: count, dtype: int64

In [22]:
print(gnn_df["Hour"].describe())

count    2.047088e+06
mean     1.357559e+01
std      5.145026e+00
min      0.000000e+00
25%      1.000000e+01
50%      1.400000e+01
75%      1.700000e+01
max      2.300000e+01
Name: Hour, dtype: float64

In [26]:
feature_groups = {
    # Features not encoded and having direct relevant features
    "Location": [
        "Latitude",
        "Longitude"
    ],

    "Road": [
        "1st_Road_Number",
        "2nd_Road_Number",
        "Speed_limit"
    ],

    "Time": [
        "Year",
        "Month",
        "Day",
        "Hour",
        "Is_Weekend",
        "Is_Rush_Hour",
        "Is_Peak_Hour",
        "Is_Night",
        "Is_Morning",
        "Is_Evening"
    ],

    "Environment": [
        "Bad_Weather_Flag",
        "Poor_Visibility_Flag"
    ],

    # Using loop for the ENCODED COLUMNS as I have the original column,
    # I would check the column starting with the main col name and append it in the dictionary
    "Road_Type": [col for col in gnn_df.columns if col.startswith("Road_Type_")],
    "Road_Class": [col for col in gnn_df.columns if col.startswith("1st_Road_Class_") or col.startswith("2nd_Road_Class_")],
    "Junction": [col for col in gnn_df.columns if col.startswith("Junction_")],
    "Weather": [col for col in gnn_df.columns if col.startswith("Weather_Conditions_")],
    "Road_Surface": [col for col in gnn_df.columns if col.startswith("Road_Surface_Conditions_")],
    "Lighting": [col for col in gnn_df.columns if col.startswith("Light_Conditions_")],
    "Area": [col for col in gnn_df.columns if col.startswith("Urban_or_Rural_Area_")],
    "Traffic": [col for col in gnn_df.columns if col.startswith("Traffic_Density_Indicator_")],
    "Season": [col for col in gnn_df.columns if col.startswith("Season_")]
}

In [27]:
for group, features in feature_groups.items():
    # print(f"{group}: {columns}")
    print(f"\n {"-"*20} {group} {"-"*20}\n")
    print(features)

 -------------------- Location --------------------

['Latitude', 'Longitude']

 -------------------- Road --------------------

['1st_Road_Number', '2nd_Road_Number', 'Speed_limit']

 -------------------- Time --------------------

['Year', 'Month', 'Day', 'Hour', 'Is_Weekend', 'Is_Rush_Hour', 'Is_Peak_Hour', 'Is_Night', 'Is_Morning', 'Is_Evening']

 -------------------- Environment --------------------

['Bad_Weather_Flag', 'Poor_Visibility_Flag']

 -------------------- Road_Type --------------------

['Road_Type_Dual Carriageway', 'Road_Type_One Way Street', 'Road_Type_Roundabout', 'Road_Type_Single Carriageway', 'Road_Type_Slip Road', 'Road_Type_Unknown']

 -------------------- Road_Class --------------------

['1st_Road_Class_A', '1st_Road_Class_A(M)', '1st_Road_Class_B', '1st_Road_Class_C', '1st_Road_Class_Motorway', '1st_Road_Class_Unclassified', '2nd_Road_Class_A', '2nd_Road_Class_A(M)', '2nd_Road_Class_B', '2nd_Road_Class_C', '2nd_Road_Class_Motorway', '2nd_Road_Class_Unclassified', '2nd_Road_Class_Unknown']

 -------------------- Junction --------------------

['Junction_Control_Authorised Person', 'Junction_Control_Auto Traffic Signal', 'Junction_Control_Give Way Or Uncontrolled', 'Junction_Control_Not At Junction Or Within 20 Metres', 'Junction_Control_Stop Sign', 'Junction_Control_Unknown', 'Junction_Detail_Crossroads', 'Junction_Detail_Mini-Roundabout', 'Junction_Detail_More Than 4 Arms (Not Roundabout)', 'Junction_Detail_Not At Junction Or Within 20 Metres', 'Junction_Detail_Other Junction', 'Junction_Detail_Private Drive Or Entrance', 'Junction_Detail_Roundabout', 'Junction_Detail_Slip Road', 'Junction_Detail_T Or Staggered Junction', 'Junction_Detail_Unknown']

 -------------------- Weather --------------------

['Weather_Conditions_Fine + High Winds', 'Weather_Conditions_Fine No High Winds', 'Weather_Conditions_Fog Or Mist', 'Weather_Conditions_Other', 'Weather_Conditions_Raining + High Winds', 'Weather_Conditions_Raining No High Winds', 'Weather_Conditions_Snowing + High Winds', 'Weather_Conditions_Snowing No High Winds', 'Weather_Conditions_Unknown']

 -------------------- Road_Surface --------------------

['Road_Surface_Conditions_Dry', 'Road_Surface_Conditions_Flood Over 3Cm. Deep', 'Road_Surface_Conditions_Frost Or Ice', 'Road_Surface_Conditions_Snow', 'Road_Surface_Conditions_Unknown', 'Road_Surface_Conditions_Wet Or Damp']

 -------------------- Lighting --------------------

['Light_Conditions_Darkness - Lighting Unknown', 'Light_Conditions_Darkness - Lights Lit', 'Light_Conditions_Darkness - Lights Unlit', 'Light_Conditions_Darkness - No Lighting', 'Light_Conditions_Daylight', 'Light_Conditions_Unknown']

 -------------------- Area --------------------

['Urban_or_Rural_Area_Rural', 'Urban_or_Rural_Area_Unallocated', 'Urban_or_Rural_Area_Urban']

 -------------------- Traffic --------------------

['Traffic_Density_Indicator_Single_Vehicle', 'Traffic_Density_Indicator_Two_Vehicle', 'Traffic_Density_Indicator_Moderate', 'Traffic_Density_Indicator_High_Density']

 -------------------- Season --------------------

['Season_Autumn', 'Season_Spring', 'Season_Summer', 'Season_Unknown', 'Season_Winter']